properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  resources:

    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    ###----------------Gaming----------------###
    ### Steam ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Steam
        allowPrerelease: true
      settings:
        id: Valve.Steam
        source: winget
        Ensure: Present
    ### Epic Games Launcher ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Epic Games Launcher
        allowPrerelease: true
      settings:
        id: EpicGames.EpicGamesLauncher
        source: winget
        Ensure: Present
    ###----------------Browsers----------------###
    ### Brave ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Brave Browser
        allowPrerelease: true
      settings:
        id: Brave.Brave
        source: winget
        Ensure: Present
    ###----------------TOOLS----------------###
    ### Nilesoft Shell ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Nilesoft Shell
        allowPrerelease: true
      settings:
        id: Nilesoft.Shell
        source: winget
        Ensure: Present
    ### Postman ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Postman
        allowPrerelease: true
      settings:
        id: Postman.Postman
        source: winget
        Ensure: Present
    ### Git ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
        Ensure: Present
    ### Fork ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Fork
        allowPrerelease: true
      settings:
        id: Fork.Fork
        source: winget
        Ensure: Present
    ### Azure CLI ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure CLI
        allowPrerelease: true
      settings:
        id: Microsoft.AzureCLI
        source: winget
        Ensure: Present
    ### Azure Data Studio ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Data Studio
        allowPrerelease: true
      settings:
        id: Microsoft.AzureDataStudio
        source: winget
        Ensure: Present
    ### Azure Storage Explorer ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Storage Explorer
        allowPrerelease: true
      settings:
        id: Microsoft.Azure.StorageExplorer
        source: winget
        Ensure: Present
    ###----------------IDEs----------------###
    ### VS Code ###
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
        Ensure: Present

  configurationVersion: 0.2.0
